[workspace]
authors = ["Antoine <antoine2dufournet@gmail.com>"]
channels = [
  "https://brainvisa.info/neuro-forge",
  "conda-forge",
  "nvidia",
  "pytorch",
]
name = "noillopmahc"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[dependencies]
brainvisa = ">=6.0.28,<7"
pytorch-gpu = ">=2.1.0, <2.8.0"

[pypi-dependencies]
torchvision = "*"
pytorch-lightning = "*"
tensorboard = "*"

omegaconf = "*"